### ISSUE TITLE
Cannot find code used throughout the course

### ISSUE THREAD

**Issue by cjvaland** [PacktPublishing/jQuery-for-Application-Development-From-Fundamentals-to-jQuery-Projects-#1]
I am follwoing the course in O'Reilly's website but cannot find the recourses used throughout the course. There is only the final flash cards applciation from the course, the rest is missing.

**Comment by Sonakshis** [comment]
Hi,
Thank you so much for bringing this to our attention. We have updated the resources and code bundle for this course. Hope this helps.
